name: c2cs
on:
  push:
    branches: [ "c2cs" ]
  pull_request:
    branches: [ "c2cs" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Init
        run: |
          cd C:\ ; git clone --depth=1 https://github.com/axojhf/test-cpp -b c2cs
      - name: Setup Toolchain
        run: |
          dotnet tool install bottlenoselabs.castffi.tool -g ; dotnet tool install bottlenoselabs.c2cs.tool --global 
          cd C:\c2cs
          castffi extract global.json
          ls